docker inspect nginxbasics_wordpress1_1 | grep "\"IPAddress\":"
docker inspect nginxbasics_wordpress2_1 | grep "\"IPAddress\":"
docker inspect nginxbasics_wordpress3_1 | grep "\"IPAddress\":"
docker inspect nginxbasics_wordpress4_1 | grep "\"IPAddress\":"
docker inspect nginxbasics_wordpress5_1 | grep "\"IPAddress\":"